"""empty message

Revision ID: 131d9278d64a
Revises: ec9572d3273c
Create Date: 2019-01-09 00:50:00.940645

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '131d9278d64a'
down_revision = 'ec9572d3273c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickers', sa.Column('exchange', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickers', 'exchange')
    # ### end Alembic commands ###
