"""empty message

Revision ID: 3594dc173447
Revises: de79b3cb9f73
Create Date: 2019-01-12 04:56:03.824337

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '3594dc173447'
down_revision = 'de79b3cb9f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_black_list', 'user_identity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_black_list', sa.Column('user_identity', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
